package v1

import (
	"context"
	"fmt"
	"github.com/operator-framework/kubectl-operator/pkg/action"
	ocv1 "github.com/operator-framework/operator-controller/api/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type OperatorUninstall struct {
	config *action.Configuration

	Package string

	Logf func(string, ...interface{})
}

func NewOperatorUninstall(cfg *action.Configuration) *OperatorUninstall {
	return &OperatorUninstall{
		config: cfg,
		Logf:   func(string, ...interface{}) {},
	}
}

type ErrPackageNotFound struct {
	PackageName string
}

func (e ErrPackageNotFound) Error() string {
	return fmt.Sprintf("package %q not found", e.PackageName)
}

func (u *OperatorUninstall) Run(ctx context.Context) error {
	clusterExtension := &ocv1.ClusterExtension{}
	if err := u.config.Client.Get(ctx, types.NamespacedName{Name: u.Package}, clusterExtension); err != nil {
		if apierrors.IsNotFound(err) {
			return &ErrPackageNotFound{u.Package}
		}
		return fmt.Errorf("get clusterextension %q: %v", u.Package, err)
	}

	namespaceName := clusterExtension.Spec.Namespace
	saName := clusterExtension.Spec.ServiceAccount.Name

	serviceAccount := &corev1.ServiceAccount{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: namespaceName,
			Name:      saName,
		},
	}
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: namespaceName,
		},
	}

	var (
		clusterRoles        rbacv1.ClusterRoleList
		roles               rbacv1.RoleList
		clusterRoleBindings rbacv1.ClusterRoleBindingList
		roleBindings        rbacv1.RoleBindingList
	)
	labelSelector := client.MatchingLabels{
		"olm.operatorframework.io/kubectl-operator-autogenerated": "true",
		"olm.operatorframework.io/cluster-extension-name":         clusterExtension.Name,
	}
	if err := u.config.Client.List(ctx, &clusterRoleBindings, labelSelector); err != nil {
		return err
	}
	if err := u.config.Client.List(ctx, &roleBindings, labelSelector); err != nil {
		return err
	}
	if err := u.config.Client.List(ctx, &clusterRoles, labelSelector); err != nil {
		return err
	}
	if err := u.config.Client.List(ctx, &roles, labelSelector); err != nil {
		return err
	}
	var rbacObjects []client.Object
	for _, obj := range clusterRoles.Items {
		rbacObjects = append(rbacObjects, &obj)
	}
	for _, obj := range roles.Items {
		rbacObjects = append(rbacObjects, &obj)
	}
	for _, obj := range clusterRoleBindings.Items {
		rbacObjects = append(rbacObjects, &obj)
	}
	for _, obj := range roleBindings.Items {
		rbacObjects = append(rbacObjects, &obj)
	}

	if err := deleteAndWait(ctx, u.config.Client, clusterExtension); err != nil {
		return fmt.Errorf("delete clusterextension %q: %v", u.Package, err)
	}

	if err := deleteAndWait(ctx, u.config.Client, rbacObjects...); err != nil {
		return err
	}

	if serviceAccount.Name != "default" {
		if err := deleteAndWait(ctx, u.config.Client, serviceAccount); err != nil {
			return fmt.Errorf("delete service account %q: %v", serviceAccount.Name, err)
		}
	}
	if namespace.Name != "default" {
		if err := deleteAndWait(ctx, u.config.Client, namespace); err != nil {
			return fmt.Errorf("delete namespace %q: %v", namespace.Name, err)
		}
	}
	return nil
}
